# Generated by Django 4.2.8 on 2024-01-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('none', 'None'), ('LNews', 'Local News'), ('NNews', 'National News'), ('SNews', 'Sport News'), ('TNews', 'Tech News'), ('INews', 'International News'), ('ENews', 'Economics News'), ('SANews', 'Social News')], default='None', max_length=20),
        ),
    ]
