# Generated by Django 4.2.8 on 2024-01-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_author_alter_department_d_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('InReview', 'In Review'), ('ChangeRequested', 'Change Requested'), ('Approved', 'Approved'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
