# Generated by Django 4.2.8 on 2024-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='change_requested',
            field=models.TextField(blank=True, null=True),
        ),
    ]
